server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: admin
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**, /api/v1/clients/**
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"