server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: admin
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter
        - id: auth-service
          uri: http://localhost:8084
          predicates:
            - Path=/auth/**
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
jwt:
  secretKey: 82eac5eeb476a51cd69d7e00d51021d54c5cdc063c6eed81a6651c47c0c18979
  tokenPrefix: Bearer
  tokenExpirationPeriod: 14