server:
  port: 8081
spring:
  application:
    name: admin
  profiles:
    include:
      - producer
  datasource:
    url: jdbc:postgresql://localhost:5432/admin
    username: jshan
    password: password
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#  jpa:
#    show_sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true
logging:
  level:
    org:
      hibernate:
#        SQL: debug
        type: trace